### ISSUE TITLE
About the complete code

### ISSUE THREAD

**Issue by rxc205** [yxuansu/PlanGen#2]
Hi, sorry to disturb you!  I want to ask you when the full code (adding content_planner) will be releasing, i am very interested in you work.

**Comment by yxuansu** [comment]
> Hi, sorry to disturb you! I want to ask you when the full code (adding content_planner) will be releasing, i am very interested in you work.

Hey, thank you for your interest in our paper! We were quite busy in catching up ACL deadline recently. We will try to update the complete code soon.

**Comment by rxc205** [comment]
> > Hi, sorry to disturb you! I want to ask you when the full code (adding content_planner) will be releasing, i am very interested in you work.
> 
> Hey, thank you for your interest in our paper! We were quite busy in catching up ACL deadline recently. We will try to update the complete code soon.

OK，good luck to you !!!

**Comment by l11x0m7** [comment]
Seems that ACL 2022 deadline has already passed?

**Comment by rxc205** [comment]
> > Hi, sorry to disturb you! I want to ask you when the full code (adding content_planner) will be releasing, i am very interested in you work.
> 
> Hey, thank you for your interest in our paper! We were quite busy in catching up ACL deadline recently. We will try to update the complete code soon.

Hi man, happy new year ! but, when will the complete code release？ i am very enthusiastic to your work, thx!

**Comment by Lexlum** [comment]
> > Hi, sorry to disturb you! I want to ask you when the full code (adding content_planner) will be releasing, i am very interested in you work.
> 
> Hey, thank you for your interest in our paper! We were quite busy in catching up ACL deadline recently. We will try to update the complete code soon.

I'm sorry to bother you. Your work is very important and has benefited me a lot. But when will the full code be released? I'm very interested in your work. Thank you！

**Comment by yxuansu** [comment]
> > > Hi, sorry to disturb you! I want to ask you when the full code (adding content_planner) will be releasing, i am very interested in you work.
> > 
> > 
> > Hey, thank you for your interest in our paper! We were quite busy in catching up ACL deadline recently. We will try to update the complete code soon.
> 
> I'm sorry to bother you. Your work is very important and has benefited me a lot. But when will the full code be released? I'm very interested in your work. Thank you！

Hi @rxc205, @l11x0m7, and @ssj-hub,

Sorry for my very late update!

I have updated the part of the content planner. Please let me know if you have further questions!

Best,

Yixuan
