### ISSUE TITLE
Could you provide the processing code for RDF (WebNLG) data and the processed RDF data?

### ISSUE THREAD

**Issue by Nicoleqwerty** [yxuansu/PlanGen#3]
Hi, could you provide the processing code for RDF data and the processed RDF data with content plan? I find it difficult to parse the content plan using the method proposed in the paper because it is hard to align objects in the reference text with those in the input graph. These objects often appear in different representations in reference text and input graphs.

**Comment by Lexlum** [comment]
I have the same problem as you, I would like to ask you how to solve it.Thanks!!

**Comment by yxuansu** [comment]
> Hi, could you provide the processing code for RDF data and the processed RDF data with content plan? I find it difficult to parse the content plan using the method proposed in the paper because it is hard to align objects in the reference text with those in the input graph. These objects often appear in different representations in reference text and input graphs.

Hi,

I think you can refer to some details in this file (https://github.com/yxuansu/PlanGen/blob/main/data/data_processing.py). Hope it can help you.

Best,

Yixuan

**Comment by zwzhang123** [comment]
Could you provide the processing code for RDF (WebNLG) data and the processed RDF data? Thanks!
