### ISSUE TITLE
Require code for content planner

### ISSUE THREAD

**Issue by prajwalgatti** [yxuansu/PlanGen#4]
Hi Yixuan @yxuansu,

Your paper is an interesting read, thanks for sharing your work and code.

Could you please provide the missing code for the Content Planner module? 
I would appreciate it, even if it is an initial/unrefined version that you have at the moment.

Thanks!

**Comment by prajwalgatti** [comment]
Hi @yxuansu, could you please provide the content planning code?

**Comment by XiaoqingNLP** [comment]
@yxuansu + 1

**Comment by yxuansu** [comment]
Hi @prajwalgatti and @XiaoqingNLP,

Sorry for my very late update!

I have updated the part of the content planner. Please let me know if you have further questions!

Best,

Yixuan
