### ISSUE TITLE
isuue about content code

### ISSUE THREAD

**Issue by airsyuan** [yxuansu/PlanGen#5]
Hi Yixuan,

The paper is quite valuable and I want to reimplement the result. Could you please provide the missing code? 

Thanks!

**Comment by XiaoqingNLP** [comment]
@yxuansu

**Comment by ph1Lp** [comment]
@airsYuan @XiaoqingNLP anyway you were able to recreate this code?

**Comment by XiaoqingNLP** [comment]
what do you mean "recreate"? you can try to reproduce it .

**Comment by ph1Lp** [comment]
I meant ask -- if you tried to reproduce the content planner code, were you able to do it?
since content planner code is not being released, i am trying to code it up myself

**Comment by yxuansu** [comment]
Hi @XiaoqingNLP, @airsYuan, and @ph1Lp,

Sorry for my very late update!

I have updated the part of the content planner. Please let me know if you have further questions!

Best,

Yixuan
